// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/team_up/admin/approve": {
            "post": {
                "description": "管理员审批：包含创建组织的申请与Pro级别的认证事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/admin"
                ],
                "summary": "管理员审批",
                "parameters": [
                    {
                        "type": "string",
                        "description": "审批事件类型：organization 或者 calibration_proof",
                        "name": "approve_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "要批准的组织ID，当审批事件类型为organization时必传",
                        "name": "organization_id",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "要批准的的用户open_id，当审批事件类型为calibration_proof时必传",
                        "name": "open_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "要批准的用户运动类型，当审批事件类型为calibration_proof时必传",
                        "name": "sport_type",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/admin/get_approval_items": {
            "get": {
                "description": "管理员审批：获取待审批的事项（包括定级别为pro级别的用户或者用户创建的组织信息）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/admin"
                ],
                "summary": "待审批事项清单",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetApprovalItemsResp"
                        }
                    }
                }
            }
        },
        "/team_up/event/create": {
            "post": {
                "description": "个人或者组织创建活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "创建活动",
                "parameters": [
                    {
                        "description": "参考EventInfo Model",
                        "name": "create_event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateEventResp"
                        }
                    }
                }
            }
        },
        "/team_up/event/fields_list": {
            "post": {
                "description": "根据运动类型和城市获取场地列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "获取场地列表",
                "parameters": [
                    {
                        "description": "城市",
                        "name": "city",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "运动类型",
                        "name": "sport_type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetFieldsListResp"
                        }
                    }
                }
            }
        },
        "/team_up/event/list": {
            "post": {
                "description": "根据筛选条件获取活动列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "获取活动列表",
                "parameters": [
                    {
                        "description": "运动类型：padel, tennis, pickleball",
                        "name": "sport_type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "城市",
                        "name": "city",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "开始时间，秒级时间戳",
                        "name": "start_time",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "获取的数量",
                        "name": "num",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "偏移量",
                        "name": "offset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetEventListResp"
                        }
                    }
                }
            }
        },
        "/team_up/event/page": {
            "post": {
                "description": "活动详情页，包含活动元信息和参与的用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "获取活动详情页",
                "parameters": [
                    {
                        "description": "活动ID",
                        "name": "event_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.EventTab"
                        }
                    }
                }
            }
        },
        "/team_up/event/update": {
            "post": {
                "description": "个人或者组织更新活动元信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "更新活动元信息",
                "parameters": [
                    {
                        "description": "更新活动入参,参考EventInfo",
                        "name": "update_event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateEventResp"
                        }
                    }
                }
            }
        },
        "/team_up/event/update_scorer": {
            "post": {
                "description": "更新活动的记分员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/event"
                ],
                "summary": "更新活动的记分员",
                "parameters": [
                    {
                        "description": "详见UpdateScorerRequest定义",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/organization/create": {
            "post": {
                "description": "用户上传组织信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/organization"
                ],
                "summary": "创建组织",
                "parameters": [
                    {
                        "description": "组织名称",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "运动类型",
                        "name": "sport_type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "城市",
                        "name": "city",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "联系方式",
                        "name": "contact",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "logo图",
                        "name": "logo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "经度",
                        "name": "longitude",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "纬度",
                        "name": "latitude",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/calibrate": {
            "post": {
                "description": "获取定级问题详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "用户定级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "运动类型",
                        "name": "sport_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "问卷结构体",
                        "name": "questionnaire",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否只是计算前5题，传\\",
                        "name": "pre_calibrate",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetCalibrationQuestionsResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/confirm_login": {
            "post": {
                "description": "前端使用微信code+获取手机号的code请求服务端登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "用户登录+获取手机号",
                "parameters": [
                    {
                        "description": "静默登录的code",
                        "name": "silent_code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "获取电话号的code",
                        "name": "phone_code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ConfirmLoginResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/get_calibration_questions": {
            "post": {
                "description": "获取定级问题详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "获取定级问题",
                "parameters": [
                    {
                        "description": "获取定级问题入参",
                        "name": "sport_type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "是否需要第6题",
                        "name": "need_full",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetCalibrationQuestionsResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/get_host_info": {
            "get": {
                "description": "用户在不同运动类型下是否为“组织”身份",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "用户组织信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetHostInfoResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/get_score_result": {
            "post": {
                "description": "用户上传分数信息，服务端计算用户等级变化",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "获取记分结果",
                "parameters": [
                    {
                        "description": "参考UploadRoundInfos",
                        "name": "get_score_result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetScoreResultResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/get_scoreboard": {
            "post": {
                "description": "记分板页面，包含用户可选规则项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "记分板页面",
                "parameters": [
                    {
                        "description": "活动ID",
                        "name": "event_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetScoreboardResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/join_event": {
            "post": {
                "description": "加入活动场次",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "加入活动场次",
                "parameters": [
                    {
                        "description": "加入活动场次入参",
                        "name": "event_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "是否通过邀请链接加入",
                        "name": "is_inviting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/login": {
            "post": {
                "description": "前端使用微信code请求服务端登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "用户登录(废弃，请使用confirm_login)",
                "parameters": [
                    {
                        "description": "微信Code",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.UserLoginResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/my_tab": {
            "get": {
                "description": "包含用户信息，级别信息和参与的活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "我的页面",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GetMyTabResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/publish_score": {
            "post": {
                "description": "根据计算出的等级变化，服务端更新场次，用户的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "发布比赛结果",
                "parameters": [
                    {
                        "description": "活动ID",
                        "name": "event_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "用户详情, 参考PublishScoreBody",
                        "name": "player_detail",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/quit_event": {
            "post": {
                "description": "退出活动场次",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "退出活动场次",
                "parameters": [
                    {
                        "description": "活动ID",
                        "name": "event_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/start_scoring": {
            "post": {
                "description": "根据用户选择的规则下发对应的详细对局信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "记分详细规则",
                "parameters": [
                    {
                        "description": "用户选择的记分规则，参考StartScoringBody",
                        "name": "start_scoring",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StartScoringResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/update_phone_number": {
            "post": {
                "description": "前端获取加密的用户手机号，服务端进行解码，存储",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "获取用户手机号(废弃，请使用confirm_login)",
                "parameters": [
                    {
                        "description": "微信Code",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/update_user_info": {
            "post": {
                "description": "前端获取加密的用户手机号，服务端进行解码，存储",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "前端调用getUserProfile后调用，更新后端用户信息表",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateUserInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        },
        "/team_up/user/upload_image": {
            "post": {
                "description": "前端获取加密的用户手机号，服务端进行解码，存储",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/team_up/user"
                ],
                "summary": "前端上传文件流给服务端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片类型:organization_logo, calibration_proof, event_image, avatar_image",
                        "name": "image_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件流",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BackEndResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ConfirmLoginResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.CreateEventID": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "integer"
                }
            }
        },
        "handler.CreateEventResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.CreateEventID"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.Event": {
            "type": "object",
            "properties": {
                "current_player": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.UserInfo"
                    }
                },
                "current_player_num": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "end_time_str": {
                    "type": "string"
                },
                "even_name": {
                    "type": "string"
                },
                "event_image": {
                    "type": "string"
                },
                "field_name": {
                    "type": "string"
                },
                "game_type": {
                    "type": "string"
                },
                "highest_level": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_booked": {
                    "type": "boolean"
                },
                "is_host": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "lowest_level": {
                    "type": "number"
                },
                "match_type": {
                    "type": "string"
                },
                "max_player_num": {
                    "type": "integer"
                },
                "organization_address": {
                    "type": "string"
                },
                "organization_logo": {
                    "description": "组织图片",
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "start_time_str": {
                    "type": "string"
                },
                "status": {
                    "description": "event状态：created;full;finished",
                    "type": "string"
                },
                "weekday": {
                    "type": "string"
                }
            }
        },
        "handler.EventTab": {
            "type": "object",
            "properties": {
                "event_info": {
                    "$ref": "#/definitions/model.EventInfo"
                },
                "is_user_in": {
                    "description": "表示当前用户是否已加入此活动",
                    "type": "boolean"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                }
            }
        },
        "handler.GetApprovalItemsResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.GetApprovalItemsResult"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetApprovalItemsResult": {
            "type": "object",
            "properties": {
                "calibration_items": {
                    "description": "待审批的定位为职业的用户列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.WechatUserInfoWithoutGorm"
                    }
                },
                "organization_items": {
                    "description": "待审批的组织列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.OrganizationWithoutGorm"
                    }
                }
            }
        },
        "handler.GetCalibrationQuestionsResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Question"
                    }
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetEventListData": {
            "type": "object",
            "properties": {
                "event_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Event"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "handler.GetEventListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.GetEventListData"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetFieldsListRes": {
            "type": "object",
            "properties": {
                "fields_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Organization"
                    }
                }
            }
        },
        "handler.GetFieldsListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.GetFieldsListRes"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetHostInfoResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handler.Info"
                    }
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetMyTabResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.MyTab"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetScoreResultResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.MatchResult"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.GetScoreboardResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ScoreBoard"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.Info": {
            "type": "object",
            "properties": {
                "is_host": {
                    "type": "boolean"
                },
                "organization_id": {
                    "type": "integer"
                }
            }
        },
        "handler.LevelChange": {
            "type": "object",
            "properties": {
                "change": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "handler.LevelInfo": {
            "type": "object",
            "properties": {
                "current_level": {
                    "type": "number"
                },
                "level_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.LevelChange"
                    }
                },
                "status": {
                    "description": "定级状态：need_to_calibrate;wait_for_approve;approved(7.0以下自动审批)",
                    "type": "string"
                }
            }
        },
        "handler.MatchDetail": {
            "type": "object",
            "properties": {
                "round_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RoundInfo"
                    }
                },
                "round_target_score": {
                    "description": "目标得分",
                    "type": "integer"
                },
                "settings": {
                    "$ref": "#/definitions/handler.Settings"
                }
            }
        },
        "handler.MatchResult": {
            "type": "object",
            "properties": {
                "players_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.PlayerAfterMatch"
                    }
                },
                "round_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.UploadRoundInfo"
                    }
                }
            }
        },
        "handler.MyTab": {
            "type": "object",
            "properties": {
                "sport_type_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.SportTypeInfo"
                    }
                },
                "user_info": {
                    "$ref": "#/definitions/handler.UserInfo"
                }
            }
        },
        "handler.Organization": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "event_num": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "logo": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "组织状态：no_organization;wait_for_approve;approved",
                    "type": "string"
                }
            }
        },
        "handler.PlayerAfterMatch": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "is_calibrated": {
                    "type": "boolean"
                },
                "is_scorer": {
                    "type": "boolean"
                },
                "level": {
                    "type": "number"
                },
                "level_change": {
                    "description": "等级的变化,不对外返回",
                    "type": "number"
                },
                "level_change_str": {
                    "description": "对外返回的等级变化",
                    "type": "string"
                },
                "lose_round": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "open_id": {
                    "type": "string"
                },
                "rank": {
                    "description": "排名",
                    "type": "integer"
                },
                "tie_round": {
                    "type": "integer"
                },
                "total_score": {
                    "description": "总得分",
                    "type": "integer"
                },
                "win_round": {
                    "type": "integer"
                }
            }
        },
        "handler.RoundInfo": {
            "type": "object",
            "properties": {
                "away": {
                    "description": "客队球员",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                },
                "away_avg": {
                    "description": "客队平均分",
                    "type": "number"
                },
                "court_num": {
                    "description": "场地号",
                    "type": "integer"
                },
                "home": {
                    "description": "主队球员",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                },
                "home_avg": {
                    "description": "主队平均分",
                    "type": "number"
                },
                "round_num": {
                    "description": "轮次数",
                    "type": "integer"
                }
            }
        },
        "handler.ScoreBoard": {
            "type": "object",
            "properties": {
                "event_info": {
                    "$ref": "#/definitions/model.EventInfo"
                },
                "options": {
                    "$ref": "#/definitions/model.ScoreOptions"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                }
            }
        },
        "handler.Settings": {
            "type": "object",
            "properties": {
                "valid_scorers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                }
            }
        },
        "handler.SportTypeInfo": {
            "type": "object",
            "properties": {
                "level_info": {
                    "description": "级别信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.LevelInfo"
                        }
                    ]
                },
                "my_games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.Event"
                    }
                },
                "my_organization": {
                    "$ref": "#/definitions/handler.Organization"
                },
                "sport_type": {
                    "type": "string"
                }
            }
        },
        "handler.StartScoringResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.MatchDetail"
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "handler.UpdateUserInfoReq": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "encryptedData": {
                    "description": "包括敏感数据在内的完整用户信息的加密数据",
                    "type": "string"
                },
                "iv": {
                    "description": "加密算法的初始向量",
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "rawData": {
                    "description": "不包括敏感信息的原始数据字符串，用于计算签名",
                    "type": "string"
                },
                "signature": {
                    "description": "使用 sha1( rawData + sessionkey ) 得到字符串，用于校验用户信息",
                    "type": "string"
                }
            }
        },
        "handler.UploadRoundInfo": {
            "type": "object",
            "properties": {
                "away": {
                    "description": "客队球员",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                },
                "away_avg": {
                    "description": "客队平均分",
                    "type": "number"
                },
                "away_level_change": {
                    "type": "number"
                },
                "away_score": {
                    "description": "客队本局分数",
                    "type": "integer"
                },
                "court_num": {
                    "description": "场地号",
                    "type": "integer"
                },
                "home": {
                    "description": "主队球员",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Player"
                    }
                },
                "home_avg": {
                    "description": "主队平均分",
                    "type": "number"
                },
                "home_level_change": {
                    "type": "number"
                },
                "home_score": {
                    "description": "主队本局分数",
                    "type": "integer"
                },
                "round_num": {
                    "description": "轮次数",
                    "type": "integer"
                },
                "winner": {
                    "description": "获胜者",
                    "type": "string"
                }
            }
        },
        "handler.UserInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                }
            }
        },
        "handler.UserLoginResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "model.BackEndResp": {
            "type": "object",
            "properties": {
                "data": {},
                "err_no": {
                    "type": "integer"
                },
                "err_tips": {
                    "type": "string"
                }
            }
        },
        "model.EventInfo": {
            "description": "活动元信息",
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "creator_avatar": {
                    "description": "创建者头像",
                    "type": "string"
                },
                "creator_nickname": {
                    "description": "创建者昵称",
                    "type": "string"
                },
                "current_people": {
                    "type": "integer"
                },
                "date": {
                    "description": "日期 20060102",
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "end_time_str": {
                    "type": "string"
                },
                "event_image": {
                    "description": "活动图片（只有组织创建的活动才能上传）",
                    "type": "string"
                },
                "field_name": {
                    "type": "string"
                },
                "field_type": {
                    "description": "场地类型",
                    "type": "string"
                },
                "game_type": {
                    "description": "对局类型，solo/duo",
                    "type": "string"
                },
                "highest_level": {
                    "description": "适合的最高级别",
                    "type": "number"
                },
                "id": {
                    "description": "数据库主键",
                    "type": "integer"
                },
                "is_booked": {
                    "description": "是否已定场",
                    "type": "boolean"
                },
                "is_competitive": {
                    "description": "是否是竞赛类型",
                    "type": "boolean"
                },
                "is_draft": {
                    "description": "是否是草稿请求",
                    "type": "boolean"
                },
                "is_host": {
                    "description": "是否是组织创建",
                    "type": "boolean"
                },
                "is_public": {
                    "description": "是否是公开比赛",
                    "type": "boolean"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "lowest_level": {
                    "description": "适合的最低级别",
                    "type": "number"
                },
                "max_people_num": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization_address": {
                    "type": "string"
                },
                "organization_id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "organization_logo": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "self_join": {
                    "description": "自己是否加入",
                    "type": "boolean"
                },
                "sport_type": {
                    "description": "运动类型",
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "start_time_str": {
                    "type": "string"
                },
                "status": {
                    "description": "full, can_join, finished",
                    "type": "string"
                },
                "weekday": {
                    "description": "星期几",
                    "type": "string"
                }
            }
        },
        "model.Player": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "is_calibrated": {
                    "type": "boolean"
                },
                "is_scorer": {
                    "type": "boolean"
                },
                "level": {
                    "type": "number"
                },
                "nick_name": {
                    "type": "string"
                },
                "open_id": {
                    "type": "string"
                }
            }
        },
        "model.Question": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "q_id": {
                    "type": "integer"
                },
                "q_text": {
                    "type": "string"
                }
            }
        },
        "model.ScoreOptions": {
            "type": "object",
            "properties": {
                "available_round_target": {
                    "description": "可选的每轮目标分",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "available_score_rule": {
                    "description": "可选的记分赛制",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "field_num": {
                    "description": "比赛场地数",
                    "type": "integer"
                }
            }
        },
        "mysql.OrganizationWithoutGorm": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "详细地址",
                    "type": "string"
                },
                "city": {
                    "description": "城市",
                    "type": "string"
                },
                "contact": {
                    "description": "联系方式",
                    "type": "string"
                },
                "host_open_id": {
                    "description": "主理人openID",
                    "type": "string"
                },
                "id": {
                    "description": "组织ID",
                    "type": "integer"
                },
                "is_approved": {
                    "description": "是否通过审批",
                    "type": "integer"
                },
                "logo": {
                    "description": "组织图标logo",
                    "type": "string"
                },
                "name": {
                    "description": "组织名字",
                    "type": "string"
                },
                "reviewer": {
                    "description": "审批人",
                    "type": "string"
                },
                "sport_type": {
                    "description": "运动类型",
                    "type": "string"
                },
                "total_event_num": {
                    "description": "活动次数",
                    "type": "integer"
                }
            }
        },
        "mysql.WechatUserInfoWithoutGorm": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "微信用户头像",
                    "type": "string"
                },
                "calibration_proof": {
                    "description": "自称是pro的（定级7.0的人）需要额外提供图片",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "integer"
                },
                "is_calibrated": {
                    "description": "是否完成定级",
                    "type": "integer"
                },
                "is_host": {
                    "description": "1标识有，0标识无",
                    "type": "integer"
                },
                "is_primary": {
                    "description": "是否是主要的recprd",
                    "type": "integer"
                },
                "joined_event": {
                    "description": "参与的活动",
                    "type": "string"
                },
                "joined_group": {
                    "description": "参加的组织",
                    "type": "string"
                },
                "joined_times": {
                    "description": "参与次数",
                    "type": "integer"
                },
                "level": {
                    "description": "级别",
                    "type": "integer"
                },
                "nickname": {
                    "description": "微信用户昵称",
                    "type": "string"
                },
                "open_id": {
                    "description": "微信用户open_id",
                    "type": "string"
                },
                "organization_id": {
                    "description": "主理的组织名",
                    "type": "integer"
                },
                "phone_number": {
                    "description": "用户手机号",
                    "type": "integer"
                },
                "preference": {
                    "type": "string"
                },
                "reviewer": {
                    "description": "审批人（只有职业才需要）",
                    "type": "string"
                },
                "session_key": {
                    "description": "微信session_key 用于解密",
                    "type": "string"
                },
                "sport_type": {
                    "description": "运动类型",
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "union_id": {
                    "description": "微信用户union_id",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
